#!/bin/bash
vitals="/var/log/vitals.json"
while [ 1 -eq 1 ]
do
 if curl --fail --silent --max-time 10 --retry 5 --retry-delay 0 --retry-max-time 40 -o $vitals "http://localhost:4035/vitals?raw=true" 2>/dev/null; then
 echo "Got the vitals!"
 #echo " "
 truncate -s-1 $vitals
 echo ,'"dayMode": '$(/usr/local/bin/lv GUI_dayMode) >> $vitals
 echo ,'"carName": '$(/usr/local/bin/lv GUI_vehicleName) >> $vitals
 echo ,'"EV_tripCurrent_Miles": '$(/usr/local/bin/lv EV_tripCurrent_Miles) >> $vitals
 echo ,'"EV_tripCurrent_kWh": '$(/usr/local/bin/lv EV_tripCurrent_kWh) >> $vitals
 echo ,'"EV_tripCurrent_whpm": '$(/usr/local/bin/lv EV_tripCurrent_whpm) >> $vitals
 echo ,'"EV_tripCurrent_StartTime": '$(/usr/local/bin/lv EV_tripCurrent_StartTime) >> $vitals
 echo ,'"EV_tripCurrent_EndTime": '$(/usr/local/bin/lv EV_tripCurrent_EndTime) >> $vitals
 echo ,'"energy_added": '$(/usr/local/bin/lv GUI_chargeSessionIdealEnergyAdded) >> $vitals
 echo ,'"chargeTimeRemaining": '$(/usr/local/bin/lv VAPI_chargeTimeToFull) >> $vitals
 echo ,'"album_name": '$(/usr/local/bin/lv GUI_nowPlayingAlbum) >> $vitals
 echo ,'"song_name": '$(/usr/local/bin/lv GUI_nowPlayingTitle) >> $vitals
 echo ,'"song_artist": '$(/usr/local/bin/lv GUI_nowPlayingArtist) >> $vitals
 echo ,'"album_cover": '$(/usr/local/bin/lv GUI_nowPlayingImageHash) >> $vitals
 echo ,'"song_duration": '$(/usr/local/bin/lv GUI_nowPlayingDuration) >> $vitals
 echo ,'"song_time_elapsed": '$(/usr/local/bin/lv GUI_nowPlayingElapsed) >> $vitals
 echo , '"chargeState": '$(/usr/local/bin/lv GTW_chargeState) >> $vitals
 echo } >> $vitals
if curl --fail --silent -vX POST http://afrothunder.com/vitals.php -d @$vitals --header "Content-Type: application/json" 2>/dev/null; then
 echo "Sending the vitals!"
# echo " "
rm $vitals
 sleep 10
else
  echo "Failed to send vitals"
fi
else
  #failure
  echo "Failed to get vitals"
  sleep 10
  continue
fi
done
#EOF
